// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtfoQkkn52hfJC7JbCo6_R_Gv9oI5G8nk',
    appId: '1:855762089685:web:ed1a3d3cdc029e35a1145c',
    messagingSenderId: '855762089685',
    projectId: 'cmsc-23-b2l-npcinense-e772f',
    authDomain: 'cmsc-23-b2l-npcinense-e772f.firebaseapp.com',
    storageBucket: 'cmsc-23-b2l-npcinense-e772f.appspot.com',
    measurementId: 'G-DNN0BQ0JCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq4-F-3WfcKRTW5s6KgvxEVu8Ufz7AvMo',
    appId: '1:855762089685:android:6f9170e48b97fb79a1145c',
    messagingSenderId: '855762089685',
    projectId: 'cmsc-23-b2l-npcinense-e772f',
    storageBucket: 'cmsc-23-b2l-npcinense-e772f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2d85UIDzF7yZor5Lr4ma-EPZX1nx04mQ',
    appId: '1:855762089685:ios:f701b904bae6302ea1145c',
    messagingSenderId: '855762089685',
    projectId: 'cmsc-23-b2l-npcinense-e772f',
    storageBucket: 'cmsc-23-b2l-npcinense-e772f.appspot.com',
    iosClientId: '855762089685-qsvq2jeg20lcu3os5d0g5p9tb5ktrsni.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2d85UIDzF7yZor5Lr4ma-EPZX1nx04mQ',
    appId: '1:855762089685:ios:f701b904bae6302ea1145c',
    messagingSenderId: '855762089685',
    projectId: 'cmsc-23-b2l-npcinense-e772f',
    storageBucket: 'cmsc-23-b2l-npcinense-e772f.appspot.com',
    iosClientId: '855762089685-qsvq2jeg20lcu3os5d0g5p9tb5ktrsni.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
